# Generated by Django 4.2.1 on 2023-05-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gunsinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pistol',
            options={'verbose_name': 'Пистолет', 'verbose_name_plural': 'Пистолеты'},
        ),
    ]
